nengo_deeplearning/__init__.py
nengo_deeplearning/convnet.py
nengo_deeplearning/tests/conftest.py
nengo_deeplearning/tests/test_convnet.py
setup.cfg

Conv2d and Pool2d processes for running convolutional neural networks (convnets) in Nengo. I'll try to put an example up before too long.

Convnet processes

---

nengo_extras/convnet.py
nengo_extras/tests/test_convnet.py

Getting convnet.py working with Nengo 2.1.

Nengo 2.1 compatibility

---

README.rst
nengo_extras/__init__.py
nengo_extras/neurons.py
nengo_extras/tests/test_neurons.py

As per the discussion in https://github.com/nengo/nengo/pull/975.

Add FastLIF, which used to be nengo.LIF

---

.gitignore
examples/keras/mnist_spiking_cnn.py
nengo_extras/convnet.py
nengo_extras/keras.py
nengo_extras/tests/test_convnet.py
nengo_extras/tests/test_keras.py

Added the SoftLIF neuron layer for Keras, and a converter that will make a Nengo network from a Keras model.

Added things for Keras

---

examples/cuda_convnet/cifar10_spiking_cnn.py
examples/cuda_convnet/imagenet_spiking_cnn.py
examples/keras/mnist_spiking_cnn.py
nengo_extras/cuda_convnet.py
nengo_extras/data.py

Tools for loading and running cuda-convnet models.

cuda-convnet

---

nengo_extras/convnet.py
nengo_extras/cuda_convnet.py
nengo_extras/keras.py

The mode option allows users to specify whether they want
valid (Keras) or full (cuda-convnet) pooling.
Also added some documentation to Conv2d and Pool2d.
Addresses #13.

Added mode option to Pool2d

---

examples/vision/mnist_single_layer.ipynb
examples/vision/mnist_single_layer.py
examples/vision/mnist_single_layer_gui.py
nengo_extras/data.py
nengo_extras/vision.py

Methods for doing visual processing with NEF methods. Currently waiting on nengo/nengo#1010

NEF vision

---

nengo_extras/matplotlib.py
nengo_extras/tests/test_keras.py
nengo_extras/tests/test_matplotlib.py

An improved function for showing single images, a function for tiling images, and a function for comparing sets of images.

Added some Matplotlib code for image display

---

.gitignore
nengo_extras/dists.py
nengo_extras/tests/test_dists.py

Namely a multivariate Gaussian distribution, and a general mixture distribution (that combines other distributions in the same dimensions).

Adding some distributions

---

examples/cuda_convnet/cifar10_spiking_cnn.py
examples/cuda_convnet/imagenet_spiking_cnn.py
examples/keras/mnist_spiking_cnn.py
examples/vision/mnist_single_layer_gui.py
nengo_extras/gui.py

Function for displaying images in nengo_gui. Similar to #22, but works with current nengo_gui.

Image display

---

README.rst
nengo_extras/__init__.py
nengo_extras/data.py
nengo_extras/rc.py
nengo_extras/tests/test_data.py

Can now specify where to download and store datasets.
Also added SVHN dataset, and fixed up data loading with Python3.

Added RC configuration for storing data

---

nengo_extras/spa/tests/test_utils.py
nengo_extras/spa/utils.py

These vectors leave a target vector unchanged after a specified
number of convolutions.
Porting over nengo/nengo#743

Added function to generate cyclic vectors

---

nengo_extras/networks/__init__.py
nengo_extras/networks/product.py
nengo_extras/networks/tests/test_product.py

There have been a few instances when I wanted this old network instead of the current optimized network. The tests are the same as Nengo's product tests.

Add old product network

---

nengo_extras/learning_rules.py
nengo_extras/tests/test_learning_rules.py

This learning rule works like the delta rule in machine learning.

Added DeltaRule learning rule

---

examples/plot_spikes.ipynb
nengo_extras/matplotlib.py
nengo_extras/plot_spikes.py
nengo_extras/spa/utils.py
nengo_extras/tests/test_plot_spikes.py

This adds utilities for spike raster plots as requested in #37 based on code provided by @tcstewar.

Spikeplot utilities

---

examples/cuda_convnet/cifar10_spiking_cnn.py
nengo_extras/convnet.py
nengo_extras/cuda_convnet.py
nengo_extras/deepnetworks.py
nengo_extras/learning_rules.py
nengo_extras/probe.py
nengo_extras/tests/test_learning_rules.py
nengo_extras/utils.py

Fixing a small bug with running cuda-convnet networks, where some of the biases were being ignored.
Also fixed some flake8 errors.

Fix cudaconvnet biases

---

examples/cuda_convnet/imagenet_spiking_cnn.py
nengo_extras/convnet.py
nengo_extras/deepnetworks.py
nengo_extras/learning_rules.py
nengo_extras/neurons.py
nengo_extras/tests/test_learning_rules.py

A number of improvements made while working on my thesis. All commits are independent.

Miscellaneous improvements

---

examples/keras/mnist_spiking_cnn.py
nengo_extras/convnet.py
nengo_extras/cuda_convnet.py
nengo_extras/deepnetworks.py
nengo_extras/keras.py
nengo_extras/tests/test_keras.py

Fixed keras.py to work with new Keras/tensorflow

Fix keras.py

---

LICENSE.rst

The usual Nengo license. Should have been on here earlier, my bad!

Add a license

---

nengo_extras/keras.py
nengo_extras/tests/test_keras.py

This allows training with spiking-neuron-like noise as used in my thesis (maybe the keras.SoftLIF docstring should have a reference).

Added alpharc noise model to keras.SoftLIF

---

nengo_extras/learning_rules.py
nengo_extras/ocl.py

This allows it to be combined with other learning rules, which might be problematic when changing the decoders directly.
Closes #79.

Calculate delta signal for AML.
